# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-zik2-manager

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libQt5Bluetooth.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    An unofficial native manager for the Parrot Zik headphones family.
Version:    1.3
Release:    1
Group:      Qt/Qt
License:    Proprietary
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-zik2-manager.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
An unofficial native manager for the Parrot Zik headphones family:

  - Set different noise cancelling parameters.
  - Want to listen to music but still hear what's going on around you ? Enable Street Mode !
  - Change the way your music sound using the headphone builtin hardware equalizer and software spatializer.
  - Control basic functionnality of the old Parrot ZIK 1 with the legacy mode.
  - Demo mode to test the application without posseding the headphone.

  For more info on the Parrot Zik headphones please see the official products page : http://www.parrot.com/usa/products/zik2/


  Developer note:
  This app use a modified version of QtBluetooth 5.4 that has been backported to Sailfish OS. Source is available here : https://github.com/lainwir3d/qtconnectivity/tree/5.4_sailfish_backport


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 CONFIG+=sailfish

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}
%attr(755,-,-) %{_datadir}/%{name}
%attr(644,-,-) %{_datadir}/%{name}/qml/*.qml
%exclude %{_datadir}/%{name}/qml/*.qrc
%attr(644,-,-) %{_datadir}/%{name}/qml/cover/*
%attr(644,-,-) %{_datadir}/%{name}/qml/pages_zik2/*
%attr(644,-,-) %{_datadir}/%{name}/lib/*
#%attr(755,-,-) %{_datadir}/%{name}/bin/*
%{_datadir}/applications
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
# >> files
# << files
